; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27027.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\giplash\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
